name: Check LGTM label

on:
  pull_request:
    types: [ opened, synchronize, reopened, labeled, unlabeled ]
    paths:
      - 'base-*/**'
      - 'core-*/**'
      - 'extra-*/**'

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Check lgtm label
        uses: actions/github-script@v5
        with:
          script: |
            if (${{!contains(github.event.pull_request.labels.*.name, 'lgtm')}}) throw 'Code review required - please add the "lgtm" label if build scripts satisfies the Package Styling Manual.';
