name: Test GitHub Action
on: [pull_request]

jobs:
  run:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Actions Repository
      uses: actions/checkout@v4

    - uses: jitterbit/get-changed-files@v1
      with:
        # Format of the steps output context.
        # Can be 'space-delimited', 'csv', or 'json'.
        # Default: 'space-delimited'
        format: 'space-delimited'

    - name: Check spelling of file.txt
      uses: crate-ci/typos@master
      with:
        files: ${{ steps.files.outputs.added_modified }}
